### ISSUE TITLE
Discord help

### ISSUE THREAD

**Issue by R-Yuliya** [wristcry/defthack-decompiled#2]
Добавь меня в Discord, пожалуйста.
Zef#0284

**Comment by wristcry** [comment]
Было 3 заявки, все отменил, соре
Кинь еще раз - добавлю
OwO#7663

бтв хотел тебе сам кинуть инв, но тут ты как бы вот да
![image](https://user-images.githubusercontent.com/32246563/73821604-59644000-4805-11ea-902a-3dac36644a3a.png)
